
# PurePerms by 64FF00 (xktiverz@gmail.com, @64ff00 for Twitter)

name: PurePerms
main: _64FF00\PurePerms\PurePerms
version: "2.1.7"
api: [2.0.0]
load: STARTUP
author: 64FF00
website: https://github.com/PurePlugins/PurePerms
permissions:
  pperms:
    description: "PurePerms by 64FF00! (Twitter: @64FF00)"
    children:
      pperms.command:
        description: "Allows you to use all PurePerms commands."
        children:
          pperms.command.addgroup:
            description: "Allows you to add a new group to the groups list."
          pperms.command.fperms:
            description: "Allows you to find permissions for a specific plugin."
          pperms.command.groups:
            description: "Allows you to see a list of all groups."
          pperms.command.listgperms:
            description: "Allows you to see a list of all permissions from a group."
          pperms.command.listuperms:
            description: "Allows you to see a list of all permissions from a user."
          pperms.command.ppinfo:
            description: "Allows you to get current PurePerms information."
          pperms.command.ppreload:
            description: "Allows you to reload all PurePerms configurations."
          pperms.command.removegroup:
            description: "Allows you to remove a group from the groups list."
          pperms.command.setgperm:
            description: "Allows you to add a permission to the group."
          pperms.command.setgroup:
            description: "Allows you to set group for a user."
          pperms.command.setuperm:
            description: "Allows you to add a permission to a user."
          pperms.command.unsetgperm:
            description: "Allows you to remove a permission from the group."
          pperms.command.unsetuperm:
            description: "Allows you to remove a permission from the user."
          pperms.command.usrinfo:
            description: "Allows you to see info about a user."
